name: Build Tarang App

on:
  push:
    branches: [ master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle & Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x Vi17-Android/gradlew

      - name: Build Android APK
        run: cd Vi17-Android && ./gradlew assembleDebug --stacktrace

      - name: Find APK
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tarang-APK
          path: "**/*.apk"
